name: Hello World

sudo: required
language: java

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

before_install:
  - mvn clean install

script:
  - java --version
  - mvn -X version


