name: Hello World

sudo: required
language: java

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

before_install:
  - mvn clean install

script:
  - java --version
  - mvn -f Java/NOCR/Service/pom.xml clean
  - mvn -f Java/NOCR/Service/pom.xml test
  - mvn -f Java/NOCR/Service/pom.xml verify

