name: Hello World

sudo: required
language: java

jdk:
  - openjdk8

# script: "mvn cobertura:cobertura"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

before_install:
  - mvn -f Java/NOCR/Enumeration/pom.xml clean install
  - mvn -f Java/NOCR/Constants/pom.xml clean install
  - mvn -f Java/NOCR/Database/pom.xml clean install
  - mvn -f Java/NOCR/Encapsulation/pom.xml clean install
  - mvn -f Java/NOCR/Messages/pom.xml clean install
  - mvn -f Java/NOCR/Security/pom.xml clean install
  - mvn -f Java/NOCR/Stub/pom.xml clean install
  - mvn -f Java/NOCR/Usb/pom.xml clean install
  - mvn -f Java/NOCR/Wrapper/pom.xml clean install
  - mvn -f Java/NOCR/Service/pom.xml clean

script:
  - mvn -f Java/NOCR/Service/pom.xml test
  - mvn -f Java/NOCR/Service/pom.xml package

after_success:
  - bash <(curl -s https://codecov.io/bash)